name: sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 1.0.0
homepage: https://github.com/faisalramdan17/sheet_localization_generator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 

  http: ^0.13.3
  csv: ^5.0.0
  recase: ^4.0.0
  dart_style: ^2.0.1
  source_gen: ^1.0.1
  flutter_sheet_localization: ^5.1.0
  build: ^2.0.2
  collection: ^1.15.0
  intl: ^0.17.0
  localization_builder: ^0.15.6

  meta: ^1.3.0
  analyzer: ^1.7.1
  code_builder: ^4.0.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.0.4
